[package]
name = "awk"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8"
pest_derive = "2.8"
clap = { version = "4", features = ["derive"] }
regex = "1.5"
anyhow = "1"
lazy_static = "1.4"